In [1]:
import pandas
pandas.__version__

'0.24.2'

In [2]:
import pandas as pd

In [3]:
pd?

In [4]:
import numpy as np

# 3.2 Pandas对象简介

## 3.2.1 Pandas的Series对象

In [5]:
data = pd.Series([0.25,0.5,0.75,1.0])

In [6]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [10]:
data = pd.Series([0.25,0.5,0.75,1.0],index = ['a','b','c','d'])

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [12]:
data['b']

0.5

In [14]:
population_dict = {'California' :38332521,
                   'Texas':26448193,
                   'New York':19651127,
                   'Florida':19552860,
                   'Illinois':12882135}
population = pd.Series(population_dict)

In [15]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [17]:
area_dict = {'California' :423967,
            'Texas':695662,
            'New York':141297,
            'Florida':170312,
            'Illinois':149995}
area = pd.Series(area_dict)

In [18]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [19]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

## 3.2.2 Pandas的DataFrame对象

In [20]:
states = pd.DataFrame({'population':population,
                      'area':area})

In [21]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [22]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

In [25]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [26]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### 创造DataFrame对象的方式

#### 1.通过单个Series对象创造

In [27]:
pd.DataFrame(population,columns = ['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### 2.通过字典列表创建

In [28]:
data = [{'a':i,'b':2*i} for i in range(3)]

In [29]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [30]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

#### 即使字典中有些key不存在，Pandas也会用NaN来表示

In [32]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### 3.通过Series对象字典创建

In [33]:
pd.DataFrame({'population':population,'area':area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### 4.通过NumPy二维数组创建

In [34]:
pd.DataFrame(np.random.rand(3,2),columns = ['foo','bar'],index = ['a','b','c'])

foo       bar
a  0.379940  0.553927
b  0.480903  0.783420
c  0.220847  0.556279

#### 5.通过NumPy结构化数组创建

In [2]:
import numpy as np
import pandas as pd

In [3]:
A = np.zeros(3,dtype = [('A','i8'),('B','f8')])

In [4]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [5]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## 3.2.3 Pandas的Index对象

In [6]:
ind = pd.Index([2,3,5,7,11])

In [7]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [8]:
ind[1]

3

In [9]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [11]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [12]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [13]:
indA&indB

Int64Index([3, 5, 7], dtype='int64')

In [14]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [15]:
indA ^  indB

Int64Index([1, 2, 9, 11], dtype='int64')

# 3.3 数据取值与选择

## 3.3.1 Series数据选择方法

In [16]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [17]:
data['b']

0.5

In [18]:
'a' in data

True

In [19]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [20]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [21]:
data['e'] = 1.25

In [22]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [23]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [24]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [25]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [26]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [27]:
data = pd.Series(['a','b','c'],index = [1,3,5])

In [28]:
data

1    a
3    b
5    c
dtype: object

In [29]:
data[1]

'a'

In [30]:
data[3]

'b'

In [31]:
data[1:3] #切片操作是隐式索引

3    b
5    c
dtype: object

In [32]:
data.loc[1]

'a'

In [33]:
data.loc[1:3] #loc属性表示取值和切片都是显式

1    a
3    b
dtype: object

In [34]:
data.iloc[1]

'b'

In [35]:
data.iloc[2] #iloc属性表示取值和切片都是Python形式的隐式索引

'c'

In [36]:
data.iloc[1:3]

3    b
5    c
dtype: object

## 3.3.2 DataFrame数据选择方法

In [37]:
population_dict = {'California' :38332521,
                   'Texas':26448193,
                   'New York':19651127,
                   'Florida':19552860,
                   'Illinois':12882135}
population = pd.Series(population_dict)

area_dict = {'California' :423967,
            'Texas':695662,
            'New York':141297,
            'Florida':170312,
            'Illinois':149995}
area = pd.Series(area_dict)

In [38]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [39]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [41]:
data = pd.DataFrame({'area':area,'popualtion':population})

In [42]:
data

area  popualtion
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [43]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
data['popualtion']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: popualtion, dtype: int64

In [45]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [48]:
data.popualtion

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: popualtion, dtype: int64

In [49]:
data.area is data['area']

True

In [51]:
data['density'] = data['popualtion'] /data['area']

In [52]:
data

area  popualtion     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [53]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [54]:
data.T

California         Texas      New York       Florida  \
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
popualtion  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
area        1.499950e+05  
popualtion  1.288214e+07  
density     8.588376e+01

In [55]:
data

area  popualtion     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [56]:
data.T.values

array([[4.23967000e+05, 6.95662000e+05, 1.41297000e+05, 1.70312000e+05,
        1.49995000e+05],
       [3.83325210e+07, 2.64481930e+07, 1.96511270e+07, 1.95528600e+07,
        1.28821350e+07],
       [9.04139261e+01, 3.80187404e+01, 1.39076746e+02, 1.14806121e+02,
        8.58837628e+01]])

In [57]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [58]:
data.values[1]

array([6.95662000e+05, 2.64481930e+07, 3.80187404e+01])

In [59]:
data.iloc[:3,:2]

area  popualtion
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [60]:
data.loc[:'New York',:'popualtion']

area  popualtion
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [61]:
data.ix[:3,:'popualtion']

d:\py\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area  popualtion
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [62]:
data

area  popualtion     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [64]:
data.loc[data.density >100 ,['area','density']]

area     density
New York  141297  139.076746
Florida   170312  114.806121

In [65]:
data.iloc[0,2] = 90

In [66]:
data

area  popualtion     density
California  423967    38332521   90.000000
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [67]:
data[1:3]

area  popualtion     density
Texas     695662    26448193   38.018740
New York  141297    19651127  139.076746

In [68]:
data[data.density>100]

area  popualtion     density
New York  141297    19651127  139.076746
Florida   170312    19552860  114.806121

# 3.4 Pandas数值运算方法

## 3.4.1 通用函数：保留索引

In [69]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [70]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns = ['A','B','C','D'])

In [71]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [72]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [73]:
np.sin(df * np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## 3.4.2 通用函数：索引对齐

In [74]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [75]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [76]:
population/area

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
dtype: float64

In [77]:
A = pd.Series([2,4,6],index =[0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])

In [78]:
A + B 

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [79]:
A.add(B,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [82]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),columns = list('AB'))

In [83]:
A

A   B
0   0  11
1  11  16

In [84]:
list('AB')

['A', 'B']

In [86]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('BAC'))

In [87]:
B

B  A  C
0  9  2  6
1  3  8  2
2  4  2  6

In [88]:
A+B

A     B   C
0   2.0  20.0 NaN
1  19.0  19.0 NaN
2   NaN   NaN NaN

In [89]:
fill = A.stack().mean()

In [90]:
A.add(B,fill_value = fill)

A     B     C
0   2.0  20.0  15.5
1  19.0  19.0  11.5
2  11.5  13.5  15.5

In [91]:
A

A   B
0   0  11
1  11  16

In [92]:
A**2

A    B
0    0  121
1  121  256

In [93]:
A.pow(2)

A    B
0    0  121
1  121  256

## 3.4.3 通用函数： DataFrame与Series的运算

In [95]:
A = rng.randint(10,size = (3,4))

In [96]:
A

array([[4, 8, 6, 1],
       [3, 8, 1, 9],
       [8, 9, 4, 1]])

In [98]:
A -A[0]

array([[ 0,  0,  0,  0],
       [-1,  0, -5,  8],
       [ 4,  1, -2,  0]])

In [99]:
df = pd.DataFrame(A,columns = list('QRST'))

In [100]:
df

Q  R  S  T
0  4  8  6  1
1  3  8  1  9
2  8  9  4  1

In [101]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1  0 -5  8
2  4  1 -2  0

In [102]:
df.subtract(df['R'],axis = 0)

Q  R  S  T
0 -4  0 -2 -7
1 -5  0 -7  1
2 -1  0 -5 -8

In [103]:
df.subtract(df['T'],axis =0)

Q  R  S  T
0  3  7  5  0
1 -6 -1 -8  0
2  7  8  3  0

In [104]:
halfrow = df.iloc[0,::2]

In [105]:
halfrow

Q    4
S    6
Name: 0, dtype: int32

In [106]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN -5.0 NaN
2  4.0 NaN -2.0 NaN

In [107]:
df

Q  R  S  T
0  4  8  6  1
1  3  8  1  9
2  8  9  4  1

# 3.5 处理缺失值

In [108]:
vals1 = np.array([1,None,3,4])

In [109]:
vals1

array([1, None, 3, 4], dtype=object)

In [110]:
for dtype in ['object','int']:
    print('dtype = ',dtype)
    %timeit np.arange(1E6,dtype = dtype).sum()
    print()

dtype =  object
70 ms ± 6.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
3.39 ms ± 571 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [111]:
vals2 = np.array([1,np.nan,3,4])

In [112]:
vals2.dtype

dtype('float64')

In [113]:
1 + np.nan

nan

In [114]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [115]:
vals2.sum()

nan

In [116]:
np.nansum(vals2)

8.0

In [117]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [118]:
data = pd.Series([1,np.nan,'hello',None])

In [119]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [120]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [121]:
data.dropna()

0        1
2    hello
dtype: object

In [122]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [123]:
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [124]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [125]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [126]:
df.dropna(axis ='columns')

2
0  2
1  5
2  6

In [127]:
df[3] = np.nan

In [128]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [129]:
df.dropna(axis = 'columns',how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [130]:
df.dropna(axis = 'columns',how ='any')

2
0  2
1  5
2  6

In [133]:
df.dropna(axis = 'rows',thresh = 2)

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([(1,'Kolter','Zico'),
                   (2,'Xi','Edgar'),
                   (3,'Lee','Mark'),
                   (4,'Mani','Shouvik'),
                   (5,'Gates','Bill'),
                   (6,'Musk','Elon')],columns = ['Person ID','Last Name','First Name'])

In [3]:
df.set_index('Person ID',inplace = True)

In [4]:
df

Last Name First Name
Person ID                     
1            Kolter       Zico
2                Xi      Edgar
3               Lee       Mark
4              Mani    Shouvik
5             Gates       Bill
6              Musk       Elon

In [5]:
df.loc[:,'Last Name']

Person ID
1    Kolter
2        Xi
3       Lee
4      Mani
5     Gates
6      Musk
Name: Last Name, dtype: object

In [6]:
df.loc[:,['Last Name']]

Last Name
Person ID          
1            Kolter
2                Xi
3               Lee
4              Mani
5             Gates
6              Musk

In [7]:
df.loc[[1,2],:]

Last Name First Name
Person ID                     
1            Kolter       Zico
2                Xi      Edgar

In [8]:
df.loc[1,'Last Name'] = 'Kilter'

In [9]:
df

Last Name First Name
Person ID                     
1            Kilter       Zico
2                Xi      Edgar
3               Lee       Mark
4              Mani    Shouvik
5             Gates       Bill
6              Musk       Elon

In [10]:
df.loc[7,:] = ('Moore','Andrew')

In [11]:
df

Last Name First Name
Person ID                     
1            Kilter       Zico
2                Xi      Edgar
3               Lee       Mark
4              Mani    Shouvik
5             Gates       Bill
6              Musk       Elon
7             Moore     Andrew

In [12]:
df.iloc[0,0]

'Kilter'

In [13]:
df.iloc[0,:]

Last Name     Kilter
First Name      Zico
Name: 1, dtype: object

In [18]:
df.iloc[1,:]

Last Name        Xi
First Name    Edgar
Name: 2, dtype: object

In [19]:
import sqlite3

In [20]:
conn = sqlite3.connect('people.db')

In [21]:
cursor = conn.cursor()

In [22]:
cursor.execute("""
CREATE TABLE role(
    id INTEGER PRIMARY KEY,
    name TEXT
)
""")

In [24]:
cursor.execute("INSERT INTO role VALUES (1,'Instrcutor')")


In [25]:
cursor.execute("INSERT INTO role VALUES (2,'TA')")

In [26]:
cursor.execute("INSERT INTO role VALUES (3,'Student')")

In [27]:
conn.commit()

In [28]:
for row in cursor.execute('SELECT * FROM role'):
    print(row)

(1, 'Instrcutor')
(2, 'TA')
(3, 'Student')


In [29]:
cursor.execute("""
CREATE TABLE person(
    id INTEGER PRIMARY KEY,
    last_name TEXT,
    first_name TEXT,
    role_id INTEGER
)
""")

In [30]:
cursor.execute("INSERT INTO person VALUES (1,'Kolter','Zico',1)")

In [31]:
cursor.execute("INSERT INTO person VALUES (2,'Xi','Edgar',2)")
cursor.execute("INSERT INTO person VALUES (3,'Lee','Mark',2)")
cursor.execute("INSERT INTO person VALUES (4,'Mani','Shouvik',2)")
cursor.execute("INSERT INTO person VALUES (5,'Gates','William',3)")
cursor.execute("INSERT INTO person VALUES (6,'Musk','Elon',3)")

In [32]:
conn.commit()

In [33]:
for row in cursor.execute('SELECT * FROM person'):
    print(row)

(1, 'Kolter', 'Zico', 1)
(2, 'Xi', 'Edgar', 2)
(3, 'Lee', 'Mark', 2)
(4, 'Mani', 'Shouvik', 2)
(5, 'Gates', 'William', 3)
(6, 'Musk', 'Elon', 3)


In [34]:
cursor.execute("""
CREATE TABLE grades(
    id INTEGER PRIMARY KEY,
    hw1_grade INTEGER,
    hw2_grade INTEGER
)
""")

In [35]:
cursor.execute("INSERT INTO grades VALUES (5,100,80)")

In [36]:
cursor.execute("INSERT INTO grades VALUES (6,60,80)")
cursor.execute("INSERT INTO grades VALUES (100,100,100)")

In [37]:
conn.commit()

In [38]:
for row in cursor.execute('SELECT * FROM grades'):
    print(row)

(5, 100, 80)
(6, 60, 80)
(100, 100, 100)


In [39]:
pd.read_sql_query("SELECT * FROM person",conn,index_col = 'id')

last_name first_name  role_id
id                              
1     Kolter       Zico        1
2         Xi      Edgar        2
3        Lee       Mark        2
4       Mani    Shouvik        2
5      Gates    William        3
6       Musk       Elon        3

In [41]:
pd.read_sql_query("SELECT * FROM grades",conn,index_col ="id")

hw1_grade  hw2_grade
id                       
5          100         80
6           60         80
100        100        100

In [42]:
df_person = pd.read_sql_query("SELECT * FROM person",conn,index_col = 'id')

In [43]:
df_grades = pd.read_sql_query("SELECT * FROM grades",conn,index_col ="id")

In [47]:
cursor.execute("SELECT * FROM person,grades WHERE person.id == grades.id")